//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishComposition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DishComposition()
        {
            this.MenuComposition = new HashSet<MenuComposition>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Dish { get; set; }
        public Nullable<int> Ingridient { get; set; }
        public Nullable<double> Count { get; set; }
    
        public virtual Dish Dish1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuComposition> MenuComposition { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
