//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntranceComposition
    {
        public int Id { get; set; }
        public Nullable<int> Entrance { get; set; }
        public Nullable<int> Ingredient { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Entrance Entrance1 { get; set; }
        public virtual Ingredient Ingredient1 { get; set; }
    }
}
